version: "3.8"

services:
  db:
    image: postgres
    container_name: api_example_db
    environment:
      POSTGRES_DB: api_example_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
    ports:
      - 5432:5432
    volumes:
      - api_example_db_volume:/var/lib/postgresql/data

  db_test:
    image: postgres
    container_name: api_example_db_test
    environment:
      POSTGRES_DB: api_example_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
    ports:
      - 5433:5432

volumes:
  api_example_db_volume:
